//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 04:26:22 PM IST 
//


package com.izn.schemamodeler.ui3.portal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.uiw.xml.portal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.uiw.xml.portal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PortalXMLSchema }
     * 
     */
    public PortalXMLSchema createComponent() {
        return new PortalXMLSchema();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema }
     * 
     */
    public PortalXMLSchema.Schema createComponentSchema() {
        return new PortalXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Field }
     * 
     */
    public PortalXMLSchema.Schema.Field createComponentSchemaField() {
        return new PortalXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Field.Setting }
     * 
     */
    public PortalXMLSchema.Schema.Field.Setting createComponentSchemaFieldSetting() {
        return new PortalXMLSchema.Schema.Field.Setting();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Basic }
     * 
     */
    public PortalXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new PortalXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Field.Detail }
     * 
     */
    public PortalXMLSchema.Schema.Field.Detail createComponentSchemaFieldDetail() {
        return new PortalXMLSchema.Schema.Field.Detail();
    }

    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Field.Items }
     * 
     */
    public PortalXMLSchema.Schema.Field.Items createComponentSchemaFieldItems() {
        return new PortalXMLSchema.Schema.Field.Items();
    }

    public PortalXMLSchema.Schema.Field.Items.Item createComponentSchemaFieldItemsItem() {
        return new PortalXMLSchema.Schema.Field.Items.Item();
    }
    /**
     * Create an instance of {@link PortalXMLSchema.Schema.Field.Setting.Param }
     * 
     */
    public PortalXMLSchema.Schema.Field.Setting.Param createComponentSchemaFieldSettingParam() {
        return new PortalXMLSchema.Schema.Field.Setting.Param();
    }

}
