//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 11:58:09 AM IST 
//


package com.izn.schemamodeler.ui3.page;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jabx.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jabx.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PageXMLSchema }
     * 
     */
    public PageXMLSchema createPageXMLSchema() {
        return new PageXMLSchema();
    }

    /**
     * Create an instance of {@link PageXMLSchema.Schema }
     * 
     */
    public PageXMLSchema.Schema createPageXMLSchemaSchema() {
        return new PageXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link PageXMLSchema.Schema.Field }
     * 
     */
    public PageXMLSchema.Schema.Field createPageXMLSchemaSchemaField() {
        return new PageXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link PageXMLSchema.Schema.Basic }
     * 
     */
    public PageXMLSchema.Schema.Basic createPageXMLSchemaSchemaBasic() {
        return new PageXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link PageXMLSchema.Schema.Field.Detail }
     * 
     */
    public PageXMLSchema.Schema.Field.Detail createPageXMLSchemaSchemaFieldDetail() {
        return new PageXMLSchema.Schema.Field.Detail();
    }

}
