//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 12:30:37 PM IST 
//


package com.izn.schemamodeler.admin.rule;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.admin.rule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.admin.rule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public RuleXMLSchema createRuleXMLSchema() {
        return new RuleXMLSchema();
    }

    /**
     * Create an instance of {@link Component.Schema }
     * 
     */
    public RuleXMLSchema.Schema createRuleXMLSchemaSchema() {
        return new RuleXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link Component.Schema.ObjectAcess }
     * 
     */
    public RuleXMLSchema.Schema.ObjectAcess createRuleXMLSchemaSchemaObjectAcess() {
        return new RuleXMLSchema.Schema.ObjectAcess();
    }

    /**
     * Create an instance of {@link Component.Schema.Field }
     * 
     */
    public RuleXMLSchema.Schema.Field createRuleXMLSchemaSchemaField() {
        return new RuleXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link Component.Schema.Basic }
     * 
     */
    public RuleXMLSchema.Schema.Basic createRuleXMLSchemaSchemaBasic() {
        return new RuleXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link Component.Schema.ObjectAcess.Accessdetail }
     * 
     */
    public RuleXMLSchema.Schema.ObjectAcess.Accessdetail createRuleXMLSchemaSchemaObjectAcessAccessdetail() {
        return new RuleXMLSchema.Schema.ObjectAcess.Accessdetail();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Detail }
     * 
     */
    public RuleXMLSchema.Schema.Field.Detail createRuleXMLSchemaSchemaFieldDetail() {
        return new RuleXMLSchema.Schema.Field.Detail();
    }

}
