//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 11:02:36 AM IST 
//


package com.izn.schemamodeler.system.vault;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.system.vault package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.system.vault
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public VaultXMLSchema createComponent() {
        return new VaultXMLSchema();
    }

    /**
     * Create an instance of {@link Component.Object }
     * 
     */
    public VaultXMLSchema.Object createComponentObject() {
        return new VaultXMLSchema.Object();
    }

    /**
     * Create an instance of {@link Component.Object.Field }
     * 
     */
    public VaultXMLSchema.Object.Field createComponentObjectField() {
        return new VaultXMLSchema.Object.Field();
    }

    /**
     * Create an instance of {@link Component.Object.Basic }
     * 
     */
    public VaultXMLSchema.Object.Basic createComponentObjectBasic() {
        return new VaultXMLSchema.Object.Basic();
    }

    /**
     * Create an instance of {@link Component.Object.Field.Detail }
     * 
     */
    public VaultXMLSchema.Object.Field.Detail createComponentObjectFieldDetail() {
        return new VaultXMLSchema.Object.Field.Detail();
    }

}
