//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 04:24:38 PM IST 
//


package com.izn.schemamodeler.admin.format;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.admin.format package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.admin.format
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormatXMLSchema }
     * 
     */
    public FormatXMLSchema createComponent() {
        return new FormatXMLSchema();
    }

    /**
     * Create an instance of {@link FormatXMLSchema.Schema }
     * 
     */
    public FormatXMLSchema.Schema createComponentSchema() {
        return new FormatXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link FormatXMLSchema.Schema.Field }
     * 
     */
    public FormatXMLSchema.Schema.Field createComponentSchemaField() {
        return new FormatXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link FormatXMLSchema.Schema.Basic }
     * 
     */
    public FormatXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new FormatXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link FormatXMLSchema.Schema.Field.Detail }
     * 
     */
    public FormatXMLSchema.Schema.Field.Detail createComponentSchemaFieldDetail() {
        return new FormatXMLSchema.Schema.Field.Detail();
    }

}
