//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 03:45:27 PM IST 
//


package com.izn.schemamodeler.admin.dimension;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.admin.xml.dimension package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.admin.xml.dimension
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DimensionXMLSchema }
     * 
     */
    public DimensionXMLSchema createComponent() {
        return new DimensionXMLSchema();
    }

    /**
     * Create an instance of {@link DimensionXMLSchema.Schema }
     * 
     */
    public DimensionXMLSchema.Schema createComponentSchema() {
        return new DimensionXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link DimensionXMLSchema.Schema.Field }
     * 
     */
    public DimensionXMLSchema.Schema.Field createComponentSchemaField() {
        return new DimensionXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link DimensionXMLSchema.Schema.Field.Data }
     * 
     */
    public DimensionXMLSchema.Schema.Field.Data createComponentSchemaFieldData() {
        return new DimensionXMLSchema.Schema.Field.Data();
    }

    public DimensionXMLSchema.Schema.Field.Data.Setting createComponentSchemaFieldSetting() {
        return new DimensionXMLSchema.Schema.Field.Data.Setting();
    }

    public DimensionXMLSchema.Schema.Field.Data.Setting.Param createComponentSchemaFieldSettingParam() {
        return new DimensionXMLSchema.Schema.Field.Data.Setting.Param();
    }
    /**
     * Create an instance of {@link DimensionXMLSchema.Schema.Basic }
     * 
     */
    public DimensionXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new DimensionXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link DimensionXMLSchema.Schema.Field.Data.Datadetail }
     * 
     */
    public DimensionXMLSchema.Schema.Field.Data.Datadetail createComponentSchemaFieldDataDatadetail() {
        return new DimensionXMLSchema.Schema.Field.Data.Datadetail();
    }

}
