package com.izn.schemamodeler.admin.inquiry;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.01.23 at 04:21:42 PM IST 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="schema" maxOccurs="unbounded" minOccurs="0">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="basic">
*                     &lt;complexType>
*                       &lt;simpleContent>
*                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="registryName" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/extension>
*                       &lt;/simpleContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                   &lt;element name="field">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="detail" maxOccurs="unbounded" minOccurs="0">
*                               &lt;complexType>
*                                 &lt;simpleContent>
*                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                   &lt;/extension>
*                                 &lt;/simpleContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                             &lt;element name="setting">
*                               &lt;complexType>
*                                 &lt;complexContent>
*                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                     &lt;sequence>
*                                       &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
*                                         &lt;complexType>
*                                           &lt;simpleContent>
*                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                             &lt;/extension>
*                                           &lt;/simpleContent>
*                                         &lt;/complexType>
*                                       &lt;/element>
*                                     &lt;/sequence>
*                                   &lt;/restriction>
*                                 &lt;/complexContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                           &lt;/sequence>
*                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "schema"
})
@XmlRootElement(name = "component")
public class InquiryXMLSchema {

 protected List<InquiryXMLSchema.Schema> schema;
 @XmlAttribute(name = "type")
 protected String type;
 @XmlAttribute(name = "name")
 protected String name;
 @XmlAttribute(name = "version")
 protected String version;

 /**
  * Gets the value of the schema property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the schema property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getSchema().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link CommandXMLSchema.Schema }
  * 
  * 
  */
 public List<InquiryXMLSchema.Schema> getSchema() {
     if (schema == null) {
         schema = new ArrayList<InquiryXMLSchema.Schema>();
     }
     return this.schema;
 }

 /**
  * Gets the value of the type property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getType() {
     return type;
 }

 /**
  * Sets the value of the type property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setType(String value) {
     this.type = value;
 }

 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the version property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getVersion() {
     return version;
 }

 /**
  * Sets the value of the version property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setVersion(String value) {
     this.version = value;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="basic">
  *           &lt;complexType>
  *             &lt;simpleContent>
  *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                 &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                 &lt;attribute name="registryName" type="{http://www.w3.org/2001/XMLSchema}string" />
  *               &lt;/extension>
  *             &lt;/simpleContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *         &lt;element name="field">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="detail" maxOccurs="unbounded" minOccurs="0">
  *                     &lt;complexType>
  *                       &lt;simpleContent>
  *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                         &lt;/extension>
  *                       &lt;/simpleContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                   &lt;element name="setting">
  *                     &lt;complexType>
  *                       &lt;complexContent>
  *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                           &lt;sequence>
  *                             &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
  *                               &lt;complexType>
  *                                 &lt;simpleContent>
  *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                   &lt;/extension>
  *                                 &lt;/simpleContent>
  *                               &lt;/complexType>
  *                             &lt;/element>
  *                           &lt;/sequence>
  *                         &lt;/restriction>
  *                       &lt;/complexContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                 &lt;/sequence>
  *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "basic",
     "field"
 })
 public static class Schema {

     @XmlElement(required = true)
     protected InquiryXMLSchema.Schema.Basic basic;
     @XmlElement(required = true)
     protected InquiryXMLSchema.Schema.Field field;

     /**
      * Gets the value of the basic property.
      * 
      * @return
      *     possible object is
      *     {@link CommandXMLSchema.Schema.Basic }
      *     
      */
     public InquiryXMLSchema.Schema.Basic getBasic() {
         return basic;
     }

     /**
      * Sets the value of the basic property.
      * 
      * @param value
      *     allowed object is
      *     {@link CommandXMLSchema.Schema.Basic }
      *     
      */
     public void setBasic(InquiryXMLSchema.Schema.Basic value) {
         this.basic = value;
     }

     /**
      * Gets the value of the field property.
      * 
      * @return
      *     possible object is
      *     {@link CommandXMLSchema.Schema.Field }
      *     
      */
     public InquiryXMLSchema.Schema.Field getField() {
         return field;
     }

     /**
      * Sets the value of the field property.
      * 
      * @param value
      *     allowed object is
      *     {@link CommandXMLSchema.Schema.Field }
      *     
      */
     public void setField(InquiryXMLSchema.Schema.Field value) {
         this.field = value;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;simpleContent>
      *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
      *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
      *       &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}string" />
      *       &lt;attribute name="registryName" type="{http://www.w3.org/2001/XMLSchema}string" />
      *     &lt;/extension>
      *   &lt;/simpleContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "value"
     })
     public static class Basic {

         @XmlValue
         protected String value;
         @XmlAttribute(name = "name")
         protected String name;
         @XmlAttribute(name = "description")
         protected String description;
         @XmlAttribute(name = "hidden")
         protected String hidden;
         @XmlAttribute(name = "registryName")
         protected String registryName;

         /**
          * Gets the value of the value property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getValue() {
             return value;
         }

         /**
          * Sets the value of the value property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setValue(String value) {
             this.value = value;
         }

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the description property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getDescription() {
             return description;
         }

         /**
          * Sets the value of the description property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setDescription(String value) {
             this.description = value;
         }

         /**
          * Gets the value of the hidden property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getHidden() {
             return hidden;
         }

         /**
          * Sets the value of the hidden property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setHidden(String value) {
             this.hidden = value;
         }

         /**
          * Gets the value of the registryName property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getRegistryName() {
             return registryName;
         }

         /**
          * Sets the value of the registryName property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setRegistryName(String value) {
             this.registryName = value;
         }

     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="detail" maxOccurs="unbounded" minOccurs="0">
      *           &lt;complexType>
      *             &lt;simpleContent>
      *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
      *               &lt;/extension>
      *             &lt;/simpleContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *         &lt;element name="setting">
      *           &lt;complexType>
      *             &lt;complexContent>
      *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                 &lt;sequence>
      *                   &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
      *                     &lt;complexType>
      *                       &lt;simpleContent>
      *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                         &lt;/extension>
      *                       &lt;/simpleContent>
      *                     &lt;/complexType>
      *                   &lt;/element>
      *                 &lt;/sequence>
      *               &lt;/restriction>
      *             &lt;/complexContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *       &lt;/sequence>
      *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "detail",
         "setting"
     })
     public static class Field {

         protected List<InquiryXMLSchema.Schema.Field.Detail> detail;
         @XmlElement(required = true)
         protected InquiryXMLSchema.Schema.Field.Setting setting;
         @XmlAttribute(name = "type")
         protected String type;

         /**
          * Gets the value of the detail property.
          * 
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the detail property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getDetail().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link CommandXMLSchema.Schema.Field.Detail }
          * 
          * 
          */
         public List<InquiryXMLSchema.Schema.Field.Detail> getDetail() {
             if (detail == null) {
                 detail = new ArrayList<InquiryXMLSchema.Schema.Field.Detail>();
             }
             return this.detail;
         }

         /**
          * Gets the value of the setting property.
          * 
          * @return
          *     possible object is
          *     {@link CommandXMLSchema.Schema.Field.Setting }
          *     
          */
         public InquiryXMLSchema.Schema.Field.Setting getSetting() {
             return setting;
         }

         /**
          * Sets the value of the setting property.
          * 
          * @param value
          *     allowed object is
          *     {@link CommandXMLSchema.Schema.Field.Setting }
          *     
          */
         public void setSetting(InquiryXMLSchema.Schema.Field.Setting value) {
             this.setting = value;
         }

         /**
          * Gets the value of the type property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getType() {
             return type;
         }

         /**
          * Sets the value of the type property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setType(String value) {
             this.type = value;
         }


         /**
          * <p>Java class for anonymous complex type.
          * 
          * <p>The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;simpleContent>
          *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
          *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
          *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
          *     &lt;/extension>
          *   &lt;/simpleContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {
             "value"
         })
         public static class Detail {

             @XmlValue
             protected String value;
             @XmlAttribute(name = "name")
             protected String name;
             @XmlAttribute(name = "value")
             protected String valueAttribute;

             /**
              * Gets the value of the value property.
              * 
              * @return
              *     possible object is
              *     {@link String }
              *     
              */
             public String getValue() {
                 return value;
             }

             /**
              * Sets the value of the value property.
              * 
              * @param value
              *     allowed object is
              *     {@link String }
              *     
              */
             public void setValue(String value) {
                 this.value = value;
             }

             /**
              * Gets the value of the name property.
              * 
              * @return
              *     possible object is
              *     {@link String }
              *     
              */
             public String getName() {
                 return name;
             }

             /**
              * Sets the value of the name property.
              * 
              * @param value
              *     allowed object is
              *     {@link String }
              *     
              */
             public void setName(String value) {
                 this.name = value;
             }

             /**
              * Gets the value of the valueAttribute property.
              * 
              * @return
              *     possible object is
              *     {@link String }
              *     
              */
             public String getValueAttribute() {
                 return valueAttribute;
             }

             /**
              * Sets the value of the valueAttribute property.
              * 
              * @param value
              *     allowed object is
              *     {@link String }
              *     
              */
             public void setValueAttribute(String value) {
                 this.valueAttribute = value;
             }

         }


         /**
          * <p>Java class for anonymous complex type.
          * 
          * <p>The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
          *           &lt;complexType>
          *             &lt;simpleContent>
          *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
          *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
          *               &lt;/extension>
          *             &lt;/simpleContent>
          *           &lt;/complexType>
          *         &lt;/element>
          *       &lt;/sequence>
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {
             "param"
         })
         public static class Setting {

             protected List<InquiryXMLSchema.Schema.Field.Setting.Param> param;

             /**
              * Gets the value of the param property.
              * 
              * <p>
              * This accessor method returns a reference to the live list,
              * not a snapshot. Therefore any modification you make to the
              * returned list will be present inside the JAXB object.
              * This is why there is not a <CODE>set</CODE> method for the param property.
              * 
              * <p>
              * For example, to add a new item, do as follows:
              * <pre>
              *    getParam().add(newItem);
              * </pre>
              * 
              * 
              * <p>
              * Objects of the following type(s) are allowed in the list
              * {@link CommandXMLSchema.Schema.Field.Setting.Param }
              * 
              * 
              */
             public List<InquiryXMLSchema.Schema.Field.Setting.Param> getParam() {
                 if (param == null) {
                     param = new ArrayList<InquiryXMLSchema.Schema.Field.Setting.Param>();
                 }
                 return this.param;
             }


             /**
              * <p>Java class for anonymous complex type.
              * 
              * <p>The following schema fragment specifies the expected content contained within this class.
              * 
              * <pre>
              * &lt;complexType>
              *   &lt;simpleContent>
              *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
              *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
              *     &lt;/extension>
              *   &lt;/simpleContent>
              * &lt;/complexType>
              * </pre>
              * 
              * 
              */
             @XmlAccessorType(XmlAccessType.FIELD)
             @XmlType(name = "", propOrder = {
                 "value"
             })
             public static class Param {

                 @XmlValue
                 protected String value;
                 @XmlAttribute(name = "name")
                 protected String name;
                 @XmlAttribute(name = "value")
                 protected String valueAttribute;

                 /**
                  * Gets the value of the value property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getValue() {
                     return value;
                 }

                 /**
                  * Sets the value of the value property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setValue(String value) {
                     this.value = value;
                 }

                 /**
                  * Gets the value of the name property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getName() {
                     return name;
                 }

                 /**
                  * Sets the value of the name property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setName(String value) {
                     this.name = value;
                 }

                 /**
                  * Gets the value of the valueAttribute property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getValueAttribute() {
                     return valueAttribute;
                 }

                 /**
                  * Sets the value of the valueAttribute property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setValueAttribute(String value) {
                     this.valueAttribute = value;
                 }

             }

         }

     }

 }

}
