//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.04 at 12:40:47 PM IST 
//


package com.izn.schemamodeler.ui3.table;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.ui3.table package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.ui3.table
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public TableXMLSchema createComponent() {
        return new TableXMLSchema();
    }

    /**
     * Create an instance of {@link Component.Schema }
     * 
     */
    public TableXMLSchema.Schema createComponentSchema() {
        return new TableXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link Component.Schema.Column }
     * 
     */
    public TableXMLSchema.Schema.Column createComponentSchemaColumn() {
        return new TableXMLSchema.Schema.Column();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data }
     * 
     */
    public TableXMLSchema.Schema.Column.Data createComponentSchemaColumnData() {
        return new TableXMLSchema.Schema.Column.Data();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data.Accessdetail }
     * 
     */
    public TableXMLSchema.Schema.Column.Data.Accessdetail createComponentSchemaColumnDataAccessdetail() {
        return new TableXMLSchema.Schema.Column.Data.Accessdetail();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data.Setting }
     * 
     */
    public TableXMLSchema.Schema.Column.Data.Setting createComponentSchemaColumnDataSetting() {
        return new TableXMLSchema.Schema.Column.Data.Setting();
    }

    /**
     * Create an instance of {@link Component.Schema.Basic }
     * 
     */
    public TableXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new TableXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data.Datadetail }
     * 
     */
    public TableXMLSchema.Schema.Column.Data.Datadetail createComponentSchemaColumnDataDatadetail() {
        return new TableXMLSchema.Schema.Column.Data.Datadetail();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data.Accessdetail.Access }
     * 
     */
    public TableXMLSchema.Schema.Column.Data.Accessdetail.Access createComponentSchemaColumnDataAccessdetailAccess() {
        return new TableXMLSchema.Schema.Column.Data.Accessdetail.Access();
    }

    /**
     * Create an instance of {@link Component.Schema.Column.Data.Setting.Param }
     * 
     */
    public TableXMLSchema.Schema.Column.Data.Setting.Param createComponentSchemaColumnDataSettingParam() {
        return new TableXMLSchema.Schema.Column.Data.Setting.Param();
    }

}
