//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.20 at 10:36:54 AM IST 
//


package com.izn.schemamodeler.connection;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jaxb.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jabx.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema }
     * 
     */
    public ConnectionXMLSchema createConnectionXMLSchema() {
        return new ConnectionXMLSchema();
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema.Relationship }
     * 
     */
    public ConnectionXMLSchema.Relationship createConnectionXMLSchemaObject() {
        return new ConnectionXMLSchema.Relationship();
    }

   

    /**
     * Create an instance of {@link ConnectionXMLSchema.Relationship.AttributeInfo }
     * 
     */
    public ConnectionXMLSchema.Relationship.AttributeInfo createConnectionXMLSchemaObjectAttributeInfo() {
        return new ConnectionXMLSchema.Relationship.AttributeInfo();
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema.Relationship.Basic }
     * 
     */
    public ConnectionXMLSchema.Relationship.Basic createConnectionXMLSchemaObjectBasic() {
        return new ConnectionXMLSchema.Relationship.Basic();
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema.Relationship.Basic.Detail }
     * 
     */
    public ConnectionXMLSchema.Relationship.Basic.Detail createConnectionXMLSchemaObjectBasicDetail() {
        return new ConnectionXMLSchema.Relationship.Basic.Detail();
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema.Object.AttributeInfo.AttrDetail }
     * 
     */
    public ConnectionXMLSchema.Relationship.AttributeInfo.AttrDetail createConnectionXMLSchemaObjectAttributeInfoAttrdetail() {
        return new ConnectionXMLSchema.Relationship.AttributeInfo.AttrDetail();
    }

    /**
     * Create an instance of {@link ConnectionXMLSchema.Relationship.AttributeInfo }
     * 
     */
    public ConnectionXMLSchema.Relationship.RelationshipInfo createConnectionXMLSchemaObjectRelationshipInfo() {
        return new ConnectionXMLSchema.Relationship.RelationshipInfo();
    }
    
    /**
     * Create an instance of {@link ConnectionXMLSchema.Object.AttributeInfo.AttrDetail }
     * 
     */
    public ConnectionXMLSchema.Relationship.RelationshipInfo.RelDetail createConnectionXMLSchemaObjectRelationshipInfoReldetail() {
        return new ConnectionXMLSchema.Relationship.RelationshipInfo.RelDetail();
    }
    /**
     * Create an instance of {@link ConnectionXMLSchema.Object.AttributeInfo.AttrDetail }
     * 
     */
    public ConnectionXMLSchema.Relationship.RelationshipInfo.AttrDetail createConnectionXMLSchemaObjectRelationshipInfoRelAttrDetail() {
        return new ConnectionXMLSchema.Relationship.RelationshipInfo.AttrDetail();
    }
}