//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 03:47:06 PM IST 
//


package com.izn.schemamodeler.admin.program;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.admin.xml.program package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.admin.xml.program
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProgramXMLSchema }
     * 
     */
    public ProgramXMLSchema createComponent() {
        return new ProgramXMLSchema();
    }

    /**
     * Create an instance of {@link ProgramXMLSchema.Schema }
     * 
     */
    public ProgramXMLSchema.Schema createComponentSchema() {
        return new ProgramXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link ProgramXMLSchema.Schema.Field }
     * 
     */
    public ProgramXMLSchema.Schema.Field createComponentSchemaField() {
        return new ProgramXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link ProgramXMLSchema.Schema.Basic }
     * 
     */
    public ProgramXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new ProgramXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link ProgramXMLSchema.Schema.Field.Detail }
     * 
     */
    public ProgramXMLSchema.Schema.Field.Detail createComponentSchemaFieldDetail() {
        return new ProgramXMLSchema.Schema.Field.Detail();
    }

}
