//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 12:18:39 PM IST 
//


package com.izn.schemamodeler.ui3.command;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izn.schemamodeler.ui3.command package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izn.schemamodeler.ui3.command
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public CommandXMLSchema createComponent() {
        return new CommandXMLSchema();
    }

    /**
     * Create an instance of {@link Component.Schema }
     * 
     */
    public CommandXMLSchema.Schema createComponentSchema() {
        return new CommandXMLSchema.Schema();
    }

    /**
     * Create an instance of {@link Component.Schema.Field }
     * 
     */
    public CommandXMLSchema.Schema.Field createComponentSchemaField() {
        return new CommandXMLSchema.Schema.Field();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Accessdetail }
     * 
     */
    public CommandXMLSchema.Schema.Field.Accessdetail createComponentSchemaFieldAccessdetail() {
        return new CommandXMLSchema.Schema.Field.Accessdetail();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Setting }
     * 
     */
    public CommandXMLSchema.Schema.Field.Setting createComponentSchemaFieldSetting() {
        return new CommandXMLSchema.Schema.Field.Setting();
    }

    /**
     * Create an instance of {@link Component.Schema.Basic }
     * 
     */
    public CommandXMLSchema.Schema.Basic createComponentSchemaBasic() {
        return new CommandXMLSchema.Schema.Basic();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Detail }
     * 
     */
    public CommandXMLSchema.Schema.Field.Detail createComponentSchemaFieldDetail() {
        return new CommandXMLSchema.Schema.Field.Detail();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Accessdetail.Access }
     * 
     */
    public CommandXMLSchema.Schema.Field.Accessdetail.Access createComponentSchemaFieldAccessdetailAccess() {
        return new CommandXMLSchema.Schema.Field.Accessdetail.Access();
    }

    /**
     * Create an instance of {@link Component.Schema.Field.Setting.Param }
     * 
     */
    public CommandXMLSchema.Schema.Field.Setting.Param createComponentSchemaFieldSettingParam() {
        return new CommandXMLSchema.Schema.Field.Setting.Param();
    }

}
